[workspace]
resolver = "2"
members = ["root-node", "node", "ss-cert-gen"]

[package]
name = "node-network"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] } #序列化
