[package]
name = "share"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"                                      #错误处理
serde = { version = "1.0.197", features = ["derive"] } #序列化
x509-parser = "0.16.0"                                 #X.509证书解码
